title: "Renovating NYC: Keeping our buildings and areas from deteriorating"
description: "David Xue"

theme: jekyll-theme-slate

navbar-img: "https://www.urdesignmag.com/wordpress/wp-content/uploads/2020/09/5-reasons-building-inspection-is-a-must-before-any-renovation-projects-1.jpg"
